// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// example message when a certain feature is toggled
// applicable in both system or tenant contexts
type FeatureToggled struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureToggled) Reset()         { *m = FeatureToggled{} }
func (m *FeatureToggled) String() string { return proto.CompactTextString(m) }
func (*FeatureToggled) ProtoMessage()    {}
func (*FeatureToggled) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{0}
}

func (m *FeatureToggled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureToggled.Unmarshal(m, b)
}
func (m *FeatureToggled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureToggled.Marshal(b, m, deterministic)
}
func (m *FeatureToggled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureToggled.Merge(m, src)
}
func (m *FeatureToggled) XXX_Size() int {
	return xxx_messageInfo_FeatureToggled.Size(m)
}
func (m *FeatureToggled) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureToggled.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureToggled proto.InternalMessageInfo

func (m *FeatureToggled) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeatureToggled) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// example message for when Tenancy Manager creates a new tenant
// applicable in the system context
type TenantCreated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	SalesforceAccountId  string   `protobuf:"bytes,4,opt,name=salesforce_account_id,json=salesforceAccountId,proto3" json:"salesforce_account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantCreated) Reset()         { *m = TenantCreated{} }
func (m *TenantCreated) String() string { return proto.CompactTextString(m) }
func (*TenantCreated) ProtoMessage()    {}
func (*TenantCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{1}
}

func (m *TenantCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantCreated.Unmarshal(m, b)
}
func (m *TenantCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantCreated.Marshal(b, m, deterministic)
}
func (m *TenantCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantCreated.Merge(m, src)
}
func (m *TenantCreated) XXX_Size() int {
	return xxx_messageInfo_TenantCreated.Size(m)
}
func (m *TenantCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantCreated.DiscardUnknown(m)
}

var xxx_messageInfo_TenantCreated proto.InternalMessageInfo

func (m *TenantCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TenantCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantCreated) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TenantCreated) GetSalesforceAccountId() string {
	if m != nil {
		return m.SalesforceAccountId
	}
	return ""
}

// example message for when an order is created
// applicable in a tenant context
type OrderCreated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderReference       string   `protobuf:"bytes,2,opt,name=order_reference,json=orderReference,proto3" json:"order_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCreated) Reset()         { *m = OrderCreated{} }
func (m *OrderCreated) String() string { return proto.CompactTextString(m) }
func (*OrderCreated) ProtoMessage()    {}
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{2}
}

func (m *OrderCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreated.Unmarshal(m, b)
}
func (m *OrderCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreated.Marshal(b, m, deterministic)
}
func (m *OrderCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreated.Merge(m, src)
}
func (m *OrderCreated) XXX_Size() int {
	return xxx_messageInfo_OrderCreated.Size(m)
}
func (m *OrderCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreated.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreated proto.InternalMessageInfo

func (m *OrderCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderCreated) GetOrderReference() string {
	if m != nil {
		return m.OrderReference
	}
	return ""
}

// example message for when an order gets shipped
// applicable in a tenant context
type OrderShipped struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderReference       string               `protobuf:"bytes,2,opt,name=order_reference,json=orderReference,proto3" json:"order_reference,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderShipped) Reset()         { *m = OrderShipped{} }
func (m *OrderShipped) String() string { return proto.CompactTextString(m) }
func (*OrderShipped) ProtoMessage()    {}
func (*OrderShipped) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{3}
}

func (m *OrderShipped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderShipped.Unmarshal(m, b)
}
func (m *OrderShipped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderShipped.Marshal(b, m, deterministic)
}
func (m *OrderShipped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderShipped.Merge(m, src)
}
func (m *OrderShipped) XXX_Size() int {
	return xxx_messageInfo_OrderShipped.Size(m)
}
func (m *OrderShipped) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderShipped.DiscardUnknown(m)
}

var xxx_messageInfo_OrderShipped proto.InternalMessageInfo

func (m *OrderShipped) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderShipped) GetOrderReference() string {
	if m != nil {
		return m.OrderReference
	}
	return ""
}

func (m *OrderShipped) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

// example message for when an order is changed
// applicable in a tenant context
type OrderChanged struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderReference       string               `protobuf:"bytes,2,opt,name=order_reference,json=orderReference,proto3" json:"order_reference,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderChanged) Reset()         { *m = OrderChanged{} }
func (m *OrderChanged) String() string { return proto.CompactTextString(m) }
func (*OrderChanged) ProtoMessage()    {}
func (*OrderChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{4}
}

func (m *OrderChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderChanged.Unmarshal(m, b)
}
func (m *OrderChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderChanged.Marshal(b, m, deterministic)
}
func (m *OrderChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderChanged.Merge(m, src)
}
func (m *OrderChanged) XXX_Size() int {
	return xxx_messageInfo_OrderChanged.Size(m)
}
func (m *OrderChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderChanged.DiscardUnknown(m)
}

var xxx_messageInfo_OrderChanged proto.InternalMessageInfo

func (m *OrderChanged) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderChanged) GetOrderReference() string {
	if m != nil {
		return m.OrderReference
	}
	return ""
}

func (m *OrderChanged) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

// example message requesting that a customer gets invoiced for an order
// applicable in a tenant context
type InvoiceCustomer struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderReference       string               `protobuf:"bytes,2,opt,name=order_reference,json=orderReference,proto3" json:"order_reference,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InvoiceCustomer) Reset()         { *m = InvoiceCustomer{} }
func (m *InvoiceCustomer) String() string { return proto.CompactTextString(m) }
func (*InvoiceCustomer) ProtoMessage()    {}
func (*InvoiceCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{5}
}

func (m *InvoiceCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceCustomer.Unmarshal(m, b)
}
func (m *InvoiceCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceCustomer.Marshal(b, m, deterministic)
}
func (m *InvoiceCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceCustomer.Merge(m, src)
}
func (m *InvoiceCustomer) XXX_Size() int {
	return xxx_messageInfo_InvoiceCustomer.Size(m)
}
func (m *InvoiceCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceCustomer proto.InternalMessageInfo

func (m *InvoiceCustomer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InvoiceCustomer) GetOrderReference() string {
	if m != nil {
		return m.OrderReference
	}
	return ""
}

func (m *InvoiceCustomer) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

// example message when an order has been invoiced
// applicable in a tenant context
type OrderInvoiced struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInvoiced) Reset()         { *m = OrderInvoiced{} }
func (m *OrderInvoiced) String() string { return proto.CompactTextString(m) }
func (*OrderInvoiced) ProtoMessage()    {}
func (*OrderInvoiced) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{6}
}

func (m *OrderInvoiced) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInvoiced.Unmarshal(m, b)
}
func (m *OrderInvoiced) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInvoiced.Marshal(b, m, deterministic)
}
func (m *OrderInvoiced) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInvoiced.Merge(m, src)
}
func (m *OrderInvoiced) XXX_Size() int {
	return xxx_messageInfo_OrderInvoiced.Size(m)
}
func (m *OrderInvoiced) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInvoiced.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInvoiced proto.InternalMessageInfo

func (m *OrderInvoiced) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

// example message which provides no options
// will get default type urn, topic and version
type SimpleDefaults struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  string   `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleDefaults) Reset()         { *m = SimpleDefaults{} }
func (m *SimpleDefaults) String() string { return proto.CompactTextString(m) }
func (*SimpleDefaults) ProtoMessage()    {}
func (*SimpleDefaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{7}
}

func (m *SimpleDefaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleDefaults.Unmarshal(m, b)
}
func (m *SimpleDefaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleDefaults.Marshal(b, m, deterministic)
}
func (m *SimpleDefaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleDefaults.Merge(m, src)
}
func (m *SimpleDefaults) XXX_Size() int {
	return xxx_messageInfo_SimpleDefaults.Size(m)
}
func (m *SimpleDefaults) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleDefaults.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleDefaults proto.InternalMessageInfo

func (m *SimpleDefaults) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *SimpleDefaults) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

// example message which provides topic
// default type urn and version
type SimpleTopic struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  string   `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleTopic) Reset()         { *m = SimpleTopic{} }
func (m *SimpleTopic) String() string { return proto.CompactTextString(m) }
func (*SimpleTopic) ProtoMessage()    {}
func (*SimpleTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{8}
}

func (m *SimpleTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleTopic.Unmarshal(m, b)
}
func (m *SimpleTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleTopic.Marshal(b, m, deterministic)
}
func (m *SimpleTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleTopic.Merge(m, src)
}
func (m *SimpleTopic) XXX_Size() int {
	return xxx_messageInfo_SimpleTopic.Size(m)
}
func (m *SimpleTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleTopic.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleTopic proto.InternalMessageInfo

func (m *SimpleTopic) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *SimpleTopic) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

// example message which provides version
// default type urn and topic
type SimpleVersion struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  string   `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleVersion) Reset()         { *m = SimpleVersion{} }
func (m *SimpleVersion) String() string { return proto.CompactTextString(m) }
func (*SimpleVersion) ProtoMessage()    {}
func (*SimpleVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d2c33dd29ab6eb, []int{9}
}

func (m *SimpleVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleVersion.Unmarshal(m, b)
}
func (m *SimpleVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleVersion.Marshal(b, m, deterministic)
}
func (m *SimpleVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleVersion.Merge(m, src)
}
func (m *SimpleVersion) XXX_Size() int {
	return xxx_messageInfo_SimpleVersion.Size(m)
}
func (m *SimpleVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleVersion proto.InternalMessageInfo

func (m *SimpleVersion) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *SimpleVersion) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func init() {
	proto.RegisterType((*FeatureToggled)(nil), "eventinator.test.FeatureToggled")
	proto.RegisterType((*TenantCreated)(nil), "eventinator.test.TenantCreated")
	proto.RegisterType((*OrderCreated)(nil), "eventinator.test.OrderCreated")
	proto.RegisterType((*OrderShipped)(nil), "eventinator.test.OrderShipped")
	proto.RegisterType((*OrderChanged)(nil), "eventinator.test.OrderChanged")
	proto.RegisterType((*InvoiceCustomer)(nil), "eventinator.test.InvoiceCustomer")
	proto.RegisterType((*OrderInvoiced)(nil), "eventinator.test.OrderInvoiced")
	proto.RegisterType((*SimpleDefaults)(nil), "eventinator.test.SimpleDefaults")
	proto.RegisterType((*SimpleTopic)(nil), "eventinator.test.SimpleTopic")
	proto.RegisterType((*SimpleVersion)(nil), "eventinator.test.SimpleVersion")
}

func init() { proto.RegisterFile("examples.proto", fileDescriptor_02d2c33dd29ab6eb) }

var fileDescriptor_02d2c33dd29ab6eb = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xc1, 0x6b, 0xd4, 0x40,
	0x14, 0xc6, 0xc9, 0x36, 0xac, 0xed, 0xb4, 0x9b, 0xae, 0xd1, 0x4a, 0x5c, 0x10, 0x6b, 0x08, 0xd8,
	0xd3, 0x2c, 0x54, 0x2f, 0xbb, 0x37, 0x5d, 0x29, 0xf4, 0x20, 0x42, 0xba, 0x7a, 0xf0, 0xb2, 0xcc,
	0x26, 0x2f, 0xe9, 0x40, 0x32, 0x13, 0x66, 0x5e, 0x8a, 0x5e, 0xf7, 0xe8, 0x2d, 0x57, 0xc1, 0xff,
	0x55, 0x32, 0x93, 0xb4, 0x56, 0x56, 0x58, 0x10, 0xf4, 0x36, 0xf3, 0xde, 0x7c, 0xdf, 0xfb, 0xe5,
	0xbd, 0x99, 0x10, 0x0f, 0xbe, 0xb0, 0xb2, 0x2a, 0x40, 0xd3, 0x4a, 0x49, 0x94, 0xfe, 0x18, 0x6e,
	0x40, 0x20, 0x17, 0x0c, 0xa5, 0xa2, 0x08, 0x1a, 0x27, 0xcf, 0x73, 0x29, 0xf3, 0x02, 0xa6, 0x26,
	0xbf, 0xae, 0xb3, 0x29, 0xf2, 0x12, 0x34, 0xb2, 0xb2, 0xb2, 0x92, 0xc9, 0xc3, 0x5f, 0x25, 0x26,
	0x14, 0x7e, 0x24, 0xde, 0x05, 0x30, 0xac, 0x15, 0x2c, 0x65, 0x9e, 0x17, 0x90, 0xfa, 0x1e, 0x19,
	0xf0, 0x34, 0x70, 0x4e, 0x9d, 0xb3, 0x83, 0x78, 0xc0, 0x53, 0x3f, 0x20, 0x0f, 0x40, 0xb0, 0x75,
	0x01, 0x69, 0x30, 0x38, 0x75, 0xce, 0xf6, 0xe3, 0x7e, 0x3b, 0x7f, 0xba, 0x69, 0xa2, 0x13, 0xfd,
	0x55, 0x23, 0x94, 0x34, 0xb3, 0x26, 0x14, 0x8d, 0x4b, 0xf8, 0xdd, 0x21, 0xa3, 0x25, 0x08, 0x26,
	0x70, 0xa1, 0x80, 0xe1, 0x16, 0x5b, 0x9f, 0xb8, 0x82, 0x95, 0x60, 0x3c, 0x0f, 0x62, 0xb3, 0xf6,
	0x9f, 0x90, 0xa1, 0x82, 0x9c, 0x4b, 0x11, 0xec, 0x99, 0x68, 0xb7, 0xf3, 0xcf, 0xc9, 0x89, 0x66,
	0x05, 0xe8, 0x4c, 0xaa, 0x04, 0x56, 0x2c, 0x49, 0x64, 0x2d, 0x70, 0xc5, 0xd3, 0xc0, 0x35, 0xc7,
	0x1e, 0xdd, 0x25, 0xdf, 0xd8, 0xdc, 0xe5, 0x7d, 0x38, 0x34, 0x24, 0x34, 0xb1, 0x28, 0x21, 0x23,
	0x47, 0x1f, 0x54, 0x0a, 0xea, 0x4f, 0x68, 0x2f, 0xc9, 0xb1, 0x6c, 0xf3, 0x2b, 0x05, 0x19, 0x28,
	0x10, 0x49, 0x4f, 0xe9, 0x99, 0x70, 0xdc, 0x47, 0xe7, 0xc1, 0xa6, 0x89, 0x1e, 0x77, 0xe6, 0x26,
	0x75, 0x5b, 0xa2, 0x71, 0xba, 0x1a, 0x57, 0xd7, 0xbc, 0xaa, 0xfe, 0xa2, 0x86, 0x4f, 0x89, 0x9b,
	0x32, 0x04, 0xd3, 0x91, 0xc3, 0xf3, 0x09, 0xb5, 0x33, 0xa6, 0xfd, 0x8c, 0xe9, 0xb2, 0x9f, 0x71,
	0x6c, 0xce, 0x6d, 0x61, 0xd2, 0x16, 0xe1, 0x8e, 0x69, 0x71, 0xcd, 0x44, 0xfe, 0x7f, 0x99, 0x12,
	0x8b, 0x10, 0xfe, 0x70, 0xc8, 0xf1, 0xa5, 0xb8, 0x91, 0x3c, 0x81, 0x45, 0xad, 0x51, 0x96, 0xa0,
	0xfe, 0x1d, 0xd6, 0x8b, 0x4d, 0x13, 0x3d, 0xbb, 0x87, 0xc5, 0x2d, 0xca, 0x2a, 0xe9, 0x58, 0xc2,
	0x0b, 0x32, 0x32, 0x2d, 0xeb, 0x18, 0x53, 0x7f, 0x42, 0xf6, 0x33, 0x5e, 0x80, 0xb9, 0xba, 0x16,
	0xf1, 0x76, 0x6f, 0xaf, 0xdc, 0x36, 0xbf, 0x34, 0x7c, 0x4d, 0xbc, 0x2b, 0xde, 0xbe, 0xde, 0x77,
	0x90, 0xb1, 0xba, 0x40, 0xed, 0x8f, 0xc9, 0x5e, 0x26, 0x65, 0xe7, 0xd1, 0x2e, 0xdb, 0xc8, 0x9a,
	0xa9, 0xee, 0xdb, 0xda, 0x65, 0xb8, 0x20, 0x87, 0x56, 0xb5, 0x94, 0x15, 0x4f, 0x76, 0x91, 0xcc,
	0xc7, 0x9b, 0x26, 0x3a, 0xd2, 0x46, 0x34, 0xc5, 0x56, 0x15, 0xbe, 0x27, 0x23, 0x6b, 0xf2, 0x09,
	0x94, 0x6e, 0x5f, 0xd3, 0x2e, 0x36, 0xc1, 0xef, 0x36, 0xdf, 0x9a, 0xc8, 0x9d, 0xcd, 0xe8, 0xec,
	0xed, 0xf0, 0xb3, 0xdb, 0xfe, 0x6c, 0xd6, 0x43, 0xd3, 0xd6, 0x57, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x01, 0x9c, 0xd6, 0xa6, 0x97, 0x04, 0x00, 0x00,
}
