---
services:
  nats:
    image: nats-streaming:0.22-alpine
    command: -a 0.0.0.0 -p 4222 -m 8222 -m 8282 -c /etc/nats/nats.conf -sc /etc/nats/stan.conf -SDV
    volumes:
    - "./nats.conf:/etc/nats/nats.conf"
    - "./stan.conf:/etc/nats/stan.conf"
    - "./certs:/etc/nats/certs"

  server:
    build:
      context: .
      args:
        GO_VERSION: "1.16"
        DEBIAN_VERSION: "buster"
    command: -server nats://nats:4222 -verbose -metricsEnabled
    ports:
    - "9000:9000"
    links:
    - nats

  publisher:
    build:
      context: .
      dockerfile: ./example/publish/Dockerfile
      args:
        GO_VERSION: "1.16"
        DEBIAN_VERSION: "buster"
    command: -server server -port 5000 -verbose
    links:
    - server

  subscriber:
    build:
      context: .
      dockerfile: ./example/subscribe/Dockerfile
      args:
        GO_VERSION: "1.16"
        DEBIAN_VERSION: "buster"
    command: -server server -port 5000 -verbose
    links:
    - server
